version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: chupaca_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chupaca_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chupaca_client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: always

volumes:
  mongodb_data:
