// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90MNgqFiBLMSK3o-nhCOsRkUcN9zJ7TE',
    appId: '1:348266573319:web:0abb8e89e38ca8fc6cc4a2',
    messagingSenderId: '348266573319',
    projectId: 'chupaca-directo-uc-2026',
    authDomain: 'chupaca-directo-uc-2026.firebaseapp.com',
    storageBucket: 'chupaca-directo-uc-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARyYcRRCF80wELQGLl_4cnubctEkFYMiQ',
    appId: '1:348266573319:android:c725cba6430456b26cc4a2',
    messagingSenderId: '348266573319',
    projectId: 'chupaca-directo-uc-2026',
    storageBucket: 'chupaca-directo-uc-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2fFPHKt0xiSjBM2xW3RHqA9n9Enav5A',
    appId: '1:348266573319:ios:3655bc4f98d440196cc4a2',
    messagingSenderId: '348266573319',
    projectId: 'chupaca-directo-uc-2026',
    storageBucket: 'chupaca-directo-uc-2026.firebasestorage.app',
    iosBundleId: 'pe.edu.uncp.chupaca.chupacaDirecto',
  );
}
